services:
  - type: web
    name: web-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      # إعدادات البريد الإلكتروني
      - key: EMAIL_PROVIDER
        value: yahoo
      - key: SENDER_EMAIL
        value: your-email@yahoo.com
      - key: SENDER_PASSWORD
        value: your-app-password
      - key: RECEIVER_EMAIL
        value: your-email@yahoo.com
      - key: SMTP_SERVER
        value: smtp.mail.yahoo.com
      - key: SMTP_PORT
        value: 587
    healthCheckPath: /
    plan: free

  - type: web
    name: admin-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python admin_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10001
      # إعدادات البريد الإلكتروني
      - key: EMAIL_PROVIDER
        value: yahoo
      - key: SENDER_EMAIL
        value: your-email@yahoo.com
      - key: SENDER_PASSWORD
        value: your-app-password
      - key: RECEIVER_EMAIL
        value: your-email@yahoo.com
      - key: SMTP_SERVER
        value: smtp.mail.yahoo.com
      - key: SMTP_PORT
        value: 587
    healthCheckPath: /admin
    plan: free

databases:
  - name: web-db
    plan: free
  - name: admin-db
    plan: free